version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: plug_cowboy
    versions:
    - 2.5.0
  - dependency-name: dialyxir
    versions:
    - 1.1.0
