version: 2
jobs:
  build:
    machine:
      enabled: true
      docker_layer_caching: true
    steps:
    - checkout
    - run: "docker login -u $DOCKER_USER -p $DOCKER_PASS"
    - run: "docker build -t queer/singyeong:$(echo $CIRCLE_BRANCH | sed -e 's|/|_|g')-$CIRCLE_BUILD_NUM ."
    branches:
      ignore: master
  build-and-push:
    machine:
      enabled: true
      docker_layer_caching: true
    steps:
    - checkout
    - run: "docker login -u $DOCKER_USER -p $DOCKER_PASS"
    - run: "docker build -t queer/singyeong:$(echo $CIRCLE_BRANCH | sed -e 's|/|_|g')-$CIRCLE_BUILD_NUM ."
    - run: "docker push queer/singyeong:$(echo $CIRCLE_BRANCH | sed -e 's|/|_|g')-$CIRCLE_BUILD_NUM"
    branches:
      only: master