version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: "docker login -u $DOCKER_USER -p $DOCKER_PASS"
    - run: "docker build -t queer/singyeong:$(echo $CIRCLE_BRANCH | sed -e 's|/|_|g')-$CIRCLE_BUILD_NUM ."
  push:
    machine: true
    steps:
    - run: "docker push queer/singyeong:$(echo $CIRCLE_BRANCH | sed -e 's|/|_|g')-$CIRCLE_BUILD_NUM"

workflows:
  version: 2
  build:
    jobs:
    - build
  build-and-push:
    jobs:
    - build
    - push:
        requires:
          - build
        filters:
          branches:
            only: master